### ISSUE TITLE
Fonts are not provided by the page

### ISSUE THREAD

**Issue by andrewshadura** [slovensko-help/korona-gov#155]
The page uses Source Sans Pro as the preferred font, but doesn’t ship it as a webfont, so e.g. on my machine a local Helvetica version is getting used instead:
![Helvetica instead of Source Sans Pro](https://user-images.githubusercontent.com/309253/79955051-8926f980-847e-11ea-8063-51ecf04e349e.png)
```css
.govuk-heading-xl {
	font-family: Source Sans Pro,Arial,sans-serif;
}
```
![Helvetica](https://user-images.githubusercontent.com/309253/79955179-b2e02080-847e-11ea-919e-2f4d92208fc9.png)

Please provide the webfonts to ensure the unified look across the platforms regardless of what fonts the users have installed.
