### ISSUE TITLE
Obrazky nie su responzivne

### ISSUE THREAD

**Issue by filiplikavcan** [slovensko-help/korona-gov#37]
![1199384D-FD5A-48F4-995D-17A112C93886](https://user-images.githubusercontent.com/1244233/78819524-ab2c7080-79d6-11ea-8e0f-b83f4d9d3828.png)

**Comment by frkosk** [comment]
ID-SK ani GOVUK na to nemysleli. Navrhujem pridať obrázkom v obsahu classu `.img-fluid`
V css pridajme

```
.img-fluid {
    max-width: 100%;
    height: auto;
    vertical-align: top;
}
```

**Comment by filiplikavcan** [comment]
Pridal som toto do css:

```css
.govuk-main-wrapper img {
    width: 100%;
    max-width: 100%;
}
```
